name: neo4j-ipycytoscape 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.8
  - jupyterlab=4
  - pandas
  - ipycytoscape
  - py2neo
  - monotonic
  - openjdk=17.0.8

variables:
  NEO4J_VERSION: neo4j-community-5.12.0
  NEO4J_PASSWORD: neo4jdemo