name: neo4j-ipycytoscape 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab=4
  - pandas
  - ipycytoscape
  - py2neo
  - monotonic
  - openjdk=17.0.8

variables:
  # Neo4j local version
  NEO4J_VERSION: neo4j-community-5.12.0
  NEO4J_PASSWORD: neo4jdemo
  # Connection information for COVID-19 Community Neo4j KG server (https://github.com/covid-19-net/covid-19-community)
  DEMO_SERVER_URL: bolt://132.249.238.185:7687
  DEMO_SERVER_UN: reader
  DEMO_SERVER_PW: demo
