name: neo4j-ipycytoscape 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.8
  - jupyterlab=3
  - pandas
  - ipycytoscape
  - py2neo
  - monotonic
  - openjdk>=11.0.15

variables:
  NEO4J_VERSION: neo4j-community-4.4.9
  NEO4J_PASSWORD: demo