#!/bin/bash

VERSION="neo4j-community-4.2.0"

if [ ! -f $VERSION-unix.tar.gz ]; then
  wget http://dist.neo4j.org/$VERSION-unix.tar.gz
fi

tar -xvf $VERSION-unix.tar.gz
mv $VERSION /tmp 
rm $VERSION-unix.tar.gz

# set password 
/tmp/$VERSION/bin/neo4j-admin set-initial-password neo4jbinder

export NEO4J_HOME=/tmp/$VERSION
